### ISSUE TITLE
Can't call "evaluateJavaScript" because TurboNavigator's "session" is private

### ISSUE THREAD

**Issue by yanshiyason** [joemasilotti/TurboNavigator#22]
Hi again!

I am in the process of converting our turbo-is app to use TurboNavigator.
I noticed that there is no way for me to access the `turboNavigator.session` because the property is private.
How can I access the webView of the TurboNavigator?

What I am looking for is a way to call "evaluateJavascript" on the web view.

```swift
session.webView.evaluateJavascript('...') 
```

Any advice would be appreciated. Thank you.

**Comment by joemasilotti** [comment]
I'm currently grabbing the web view via the `VisitableVieController`. For example, in my delegate I'm doing something like this:

```swift
func controller(_ controller: VisitableViewController, forProposal proposal: VisitProposal) -> UIViewController? {
    controller.visitableView.webView?.evaluateJavaScript("...")
    return controller
}
```

You wouldn't want to evaluate the script before the view finishes loading though. My actual code attaches a button to the `VisitableViewController` and when clicked executes the script. But there's a fair amount of custom boilerplate I would need to share to have that make sense.

Is that enough for what you need? If not, I could share more of my code. Let me know!

**Comment by yanshiyason** [comment]
Hi Joe, thank you for your quick response.

You just gave me an idea.

I am in the process of writing a callback function for when the native nav bar button gets tapped.

```
@objc func handleRightBarButtonTap() {
  // in here, I have to get access to the webview
}
```

I have access to `self.turboNavigator.navigationController.topViewController` in scope, and this viewController should be a visitable view controller, so I should be able to get access to the web view.

```swift
      if let vc = self.turboNavigator.navigationController.topViewController as? VisitableViewController {
        vc.visitableView.webView?.evaluateJavaScript("...")
      }
```

Thanks again!

**Comment by joemasilotti** [comment]
That's true! Are you adding another cookbook or for your own project?

**Comment by yanshiyason** [comment]
I ran into this as I am converting my turbo-ios project to using TurboNavigator but I would be happy to write a cookbook section for it once I get it working 😄

**Comment by joemasilotti** [comment]
> I am converting my turbo-ios project to using TurboNavigator

Love to hear it! I need more battle testing #3 so any and all feedback you can offer will be much appreciated.
