### ISSUE TITLE
Duplicate definition of refresh_historical_location in demo server

### ISSUE THREAD

**Issue by arusa** [joemasilotti/TurboNavigator#36]
This seems to be defined twice in the same json:

https://github.com/joemasilotti/TurboNavigator/blob/397084bc313dfef70d7d670fce4094661b74da30/Demo/Server/app/controllers/configurations_controller.rb#L26

**Comment by arusa** [comment]
One of them should probably be "/resume_historical_location"

**Comment by joemasilotti** [comment]
Correct! Nice catch.

There's a bit more to handle with this, though. The client needs to handle the resume action, which [according to Android](https://github.com/hotwired/turbo-android/blob/c450cecc29d70eb2d6f935498b24777f89277996/turbo/src/main/kotlin/dev/hotwire/turbo/nav/TurboNavPresentation.kt#L49), is to "result in no navigation action being taken".
