### ISSUE TITLE
Default and local path configuration

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/TurboNavigator#50]
Using Turbo Navigator out of the box isn't a great experience. A lot of the routing is broken without a path configuration on a server.

I'd like to see the path configuration moved to the codebase instead of living on the demo server. Folks already have the option to override ride it without any code changes.

**Comment by jayohms** [comment]
@joemasilotti Can you clarify this a bit more? Is this purely an issue with this library + demo or a larger issue with turbo-ios?

**Comment by joemasilotti** [comment]
Good question. There are two parts that I'm contemplating.

## Demo app

The demo works great _when you hit the demo server_. But if you point it directly to your own Rails app then some of the navigation is broken because there is no path configuration present.

Moving the path configuration to the Swift demo codebase would solve that issue. But it also might hide the benefit of _remote_ configuration. A comment could help but that wouldn't be possible in the JSON file (right?).

**Question**: Is moving the file to the Swift demo codebase worth the trade-off?

## turbo-ios

I originally thought the core frameworks should handle these routes _without_ a path configuration. But then I realized the only ones we can assume will appear in "every" app are `/recede_historical_location`, `/refresh_historical_location`, and `/resume_historical_location`. Those routes are built-in to Rails already, why should the mobile developer have to route them again?

But I'm not sure it's worth the product complexity of building those into the native codebases. We'd have to make a lot of decisions around when a custom path configuration is provided – do we merge or overwrite the properties?

So I don't think it's worth bringing defaults into turbo-ios or turbo-android. What do you think?

**Comment by joemasilotti** [comment]
I was digging into Android and noticed that's exactly what the demo app does, reference a local path configuration. And so does iOS! So I think we are aligned there. I'm going to close this out for now.
