### ISSUE TITLE
Require `visitableURL` for `ProposalResult`

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/TurboNavigator#54]
Part of Turbo Navigator's handling checks if the proposed URL matches the current or previous page. When that occurs, the package replaces or pops the last controller off the stack, respectively.

It knows the page is "the same" by checking the `visitableURL` property. But this property only exists on `Visitable` controllers. Which means it works great for `VisitableViewController` and subclasses but _not for anything native_.

I'd like to require `ProposalResult.acceptCustom` to conform to a protocol with `visitableURL`. This would allow Turbo Navigator to handle these flows when native controllers are involved, too.

**Comment by jayohms** [comment]
Yes, it'd be a good idea for fully native view controllers to include the `visitableURL` and resolved path properties associated with the destination url (this makes it easy to access custom path config properties, which can be used a feature flags for a particular screen).

In `turbo-android` we have a `NavDestination` interface that all web and native fragments conform to. You can see some of the available properties here: https://github.com/hotwired/turbo-android/blob/main/turbo/src/main/kotlin/dev/hotwire/turbo/nav/TurboNavDestination.kt#L46-L63

**Comment by olivaresf** [comment]
> Yes, it'd be a good idea for fully native view controllers to include the visitableURL and resolved path properties associated with the destination url (this makes it easy to access custom path config properties, which can be used a feature flags for a particular screen).

A view controller doesn't necessarily map 1-1 to URLs, though. How does Android account for this? We could have, for example, a recipe viewer view controller that responds to both the root URL (e.g. recipes.com/) and to a list of recipes (e.g. recipes.com/my/recipes).

**Comment by joemasilotti** [comment]
> A view controller doesn't necessarily map 1-1 to URLs, though. How does Android account for this?

I'm very curious about this, too!

**Comment by joemasilotti** [comment]
Punting on this for now!
