### ISSUE TITLE
Display files using qlpreviewcontroller

### ISSUE THREAD

**Issue by lazaronixon** [joemasilotti/TurboNavigator#58]
I’m struggling with this issue maybe it applies for turbo navigator too. In hey.com it seems they display files using a qlpreviewcontroller instead of a safariviewcontroller, do you intend to provide this feature in turbo navigator ?

**Comment by joemasilotti** [comment]
Can you provide a gist or even better a repo outlining the issues you’re having? I’ve never worked with that class before so would need to do some research before being able to help.

**Comment by lazaronixon** [comment]
Specifically this piece of code:

<img width="618" alt="image" src="https://github.com/joemasilotti/TurboNavigator/assets/2651240/45a28cfa-3c27-444a-90eb-c4d8cea3e3ea">

https://github.com/hotwired/turbo-ios/blob/c476bac66f260adbfe930ed9a151e7637973ff99/Demo/SceneController.swift#L128-L136

In hey, they seem to handle it as a regular turbo navigation and display the file in a qlpreviewcontroller, but the problem is that we need to download the file first... 

<img width="293" alt="image" src="https://github.com/joemasilotti/TurboNavigator/assets/2651240/0b74bedb-fbc1-4c55-a13a-7a7bc32d4c95">

https://github.com/joemasilotti/TurboNavigator/assets/2651240/d3a6e299-35c5-4e78-8e9f-5dee73972012

**Comment by lazaronixon** [comment]
I tried to do something like this, but without success, because it can't load remote urls.

```swift
import Foundation
import QuickLook

class PreviewController: QLPreviewController, QLPreviewControllerDataSource {
    private var url: URL!
    
    convenience init(url: URL) {
        self.init()
        self.url = url
        self.dataSource = self
    }
    
    func numberOfPreviewItems(in controller: QLPreviewController) -> Int {
        return 1
    }
    
    func previewController(_ controller: QLPreviewController, previewItemAt index: Int) -> QLPreviewItem {
        return url as QLPreviewItem
    }
}
```

**Comment by joemasilotti** [comment]
> it can't load remote urls

I think that might be your answer - download the file first then use `QLPreviewController` to display it. I can't say for certain but I would guess that is what HEY is doing.

**Comment by joemasilotti** [comment]
@lazaronixon, did that work for you? If so, I'd like to close this out. Thanks!
