### ISSUE TITLE
Examples to use session and listener for js events

### ISSUE THREAD

**Issue by soyoh** [joemasilotti/TurboNavigator#60]
Hi!
I'm getting to know the project and everything around Turbo-ios and Strada.
I'd like to also use this library as it simplifies some stuff, however, I cannot find how to override or listen for JS events? either using just stimulus or Strada, 

I tried to follow some of the examples in your blog (and other issues, as in https://masilotti.com/turbo-navigator-upstream/) but I cannot get it to work 🤔 

for example, 

```
let navigator = TurboNavigator(
    preconfiguredMainSession: mainSession,
    preconfiguredModalSession: modalSession,
    delegate: self
)
```

This might be outdated? as I get errors with `extra parameters provided` 

Thanks a lot!

**Comment by joemasilotti** [comment]
It sounds like you are using an older version of the library. Which makes me realize I haven't cut a release for the latest features yet! I'll do that now.

Please reopen if that doesn't fix the issue.
