### ISSUE TITLE
basic auth is broken

### ISSUE THREAD

**Issue by yanshiyason** [joemasilotti/TurboNavigator#64]
It looks like when the "automatic displaying of ErrorPresenter on network errors" feature was merged, the basic authentication stoped working.

Here is an example of the issue using the `TurboNavigator/Demo`:

https://github.com/joemasilotti/TurboNavigator/commit/480258def4ebae3d45b27a20f0a895ac81896c70

It looks like the server is receiving the same request over and over again:

```
16:21:05 web.1  | Started GET "/" for ::1 at 2023-10-17 16:21:05 +0900
16:21:05 web.1  | Processing by DashboardsController#show as HTML
16:21:05 web.1  | Filter chain halted as :basic_auth rendered or redirected
16:21:05 web.1  | Completed 401 Unauthorized in 0ms (Allocations: 63)
16:21:05 web.1  |
16:21:05 web.1  |
16:21:05 web.1  | Started GET "/" for ::1 at 2023-10-17 16:21:05 +0900
16:21:05 web.1  | Processing by DashboardsController#show as HTML
16:21:05 web.1  | Filter chain halted as :basic_auth rendered or redirected
16:21:05 web.1  | Completed 401 Unauthorized in 0ms (Allocations: 63)
16:21:05 web.1  |
16:21:05 web.1  |
16:21:05 web.1  | Started GET "/" for ::1 at 2023-10-17 16:21:05 +0900
16:21:05 web.1  | Processing by DashboardsController#show as HTML
16:21:05 web.1  | Filter chain halted as :basic_auth rendered or redirected
16:21:05 web.1  | Completed 401 Unauthorized in 0ms (Allocations: 63)
```

**Comment by joemasilotti** [comment]
In the linked PR your Rails server is authenticating with `username` but the iOS app is using `user`. Matching them back up fixes the issue and successfully requests the page, authenticated.

Was that the issue? Or is there still something that is breaking basic auth? Admittedly, I don't use this feature much so I can't debug much more.

**Comment by yanshiyason** [comment]
Oh!!! You are right, sorry for providing a wrong example.

In my company's iOS app, I can't access the staging server due to basic auth. I am pretty sure I got the username and password right but I will check again. Thank you!
