### ISSUE TITLE
How to integrate Strada?

### ISSUE THREAD

**Issue by sevos** [joemasilotti/TurboNavigator#71]
I am struggling integrating TurboNavigator with Strada.

Strada quick start advises to implement such version of VisitableViewController:

```swift
class TurboWebViewController: VisitableViewController, BridgeDestination {

    private lazy var bridgeDelegate: BridgeDelegate = {
        BridgeDelegate(location: visitableURL.absoluteString,
                       destination: self,
                       componentTypes: BridgeComponent.allTypes)
    }()

    // MARK: View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        bridgeDelegate.onViewDidLoad()
    }

    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        bridgeDelegate.onViewWillAppear()
    }

    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        bridgeDelegate.onViewDidAppear()
    }

    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        bridgeDelegate.onViewWillDisappear()
    }

    override func viewDidDisappear(_ animated: Bool) {
        super.viewDidDisappear(animated)
        bridgeDelegate.onViewDidDisappear()
    }

    // MARK: Visitable

    override func visitableDidActivateWebView(_ webView: WKWebView) {
        bridgeDelegate.webViewDidBecomeActive(webView)
    }

    override func visitableDidDeactivateWebView() {
        bridgeDelegate.webViewDidBecomeDeactivated()
    }
}

```

I figured out the private method `TurboNavigator#controller` (sorry for ruby'ish method digests!) is responsible for the instantiation of `VisitableViewController`. I've tried to extend TurboNavigator or inherit from it, but the current visibility modifiers forbits such attempts. 

```swift
extension TurboNavigator {
    private func controller(for proposal: VisitProposal) -> UIViewController? {
        switch delegate.handle(proposal: proposal) {
        case .accept:
            return VisitableViewController(url: proposal.url)
        case .acceptCustom(let customViewController):
            return customViewController
        case .reject:
            return nil
        }
    }
}
```

The code above complains that `delegate` is private.

How would you approach this?

**Comment by joemasilotti** [comment]
This part of the README should guide you in the right direction. https://github.com/joemasilotti/TurboNavigator

1. Set the delegate of Turbo Navigator
2. Implement the function to return your controller

**Comment by marcoroth** [comment]
It's probably also worth to mention here: https://masilotti.com/strada-and-turbo-navigator/

**Comment by joemasilotti** [comment]
Thanks @marcoroth! This issue prompted that post and I totally forgot to link to it. 

@sevos, have you gotten it to work?

**Comment by sevos** [comment]
Hey @joemasilotti - Thank you so much! It works! :)

One thing that might be worth adjusting in the article would be to include "Turbo Native" string in the user agent:

```
        TurboConfig.shared.userAgent += "Turbo Native \(Strada.userAgentSubstring(for: BridgeComponent.allTypes))"
```

It's common to use `turbo_native_app?` helper in Rails and it reacts to this substring

EDIT: I see, you are just appending there, got confused, sorry!

**Comment by joemasilotti** [comment]
Awesome, glad it was helpful!
